### PR TITLE
Fix show catpure actions regardless of backend response

### PR DESCRIPTION
**Pull request by sultanmyrza**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1202462645744793) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by bafu** [comment]
@sultanmyrza After clicking the Option Menu button, the browser console showed the HTTP 404 error, and there is no notification on the screen silently. Should I expect to see a pop-up menu or an error notification?

Screenshot from 2022-06-17 20-19-27

**Steps to Reproduce**

1. Log in to my account on the Dev site.
2. Click a Photo.
3. Click the Option Menu button on the top-right corner.

**Environment**

1. Storage backend: Dev site
4. Browser: Chrome 101.0.4951.64 (Official Build) (64-bit)

**Comment by sultanmyrza** [comment]
@bafu, I think user should see at least some toast message. Can I know how you get there (aka how to reproduce your case)?

**Comment by sultanmyrza** [comment]
> @sultanmyrza After clicking the Option Menu button, the browser console showed the HTTP 404 error, and there is no notification on the screen silently. Should I expect to see a pop-up menu or an error notification?
> 
> Screenshot from 2022-06-17 20-19-27
> 
> **Steps to Reproduce**
> 
> 1. Log in to my account on the Dev site.
> 2. Click a Photo.
> 3. Click the Option Menu button on the top-right corner.
> 
> **Environment**
> 
> 1. Storage backend: Dev site
> 2. Browser: Chrome 101.0.4951.64 (Official Build) (64-bit)

@bafu, I can not reproduce the same issue here is the [[demo](https://i.imgur.com/ZEU5BrZ.mp4)], did you disable your network before step 3 (click the options menu)?

**Comment by bafu** [comment]
@sultanmyrza After clicking the Options Menu button, there are 2 issues in [my demo](https://app.claap.io/numbers-protocol/issue-for-capture-pr-1703-c-O35CsUM4Uy-A0smYUUUSTuf):

1. No pop-up menu shown from button of the screen
2. Got a HTTP 404 error

The Internet is active when I recorded the demo.

**Comment by bafu** [comment]
It seems to be an Asset compatibility issue.

Clicking the Options Menu button on a newly created Asset, the pop-up menu shows as expected.

Screenshot from 2022-06-20 14-48-49

**Comment by bafu** [comment]
@sultanmyrza The PR looks to me. :+1:

One thing to improve in the future: Clicking "Deregister from network" w/o Internet connectivity, App will show the confirmation dialog first. The UX will be even better if showing the error notification directly w/o asking the confirmation.

**Review by bafu — CHANGES_REQUESTED** [review]

**Comment by sultanmyrza** [comment]
> @sultanmyrza The PR looks to me. 👍
> 
> One thing to improve in the future: Clicking "Deregister from network" w/o Internet connectivity, App will show the confirmation dialog first, and then show the error notification after clicked the OK button.
> 
> The UX will be even better if showing the error notification directly w/o asking the confirmation.
> 
> 

For now, I just created [asana](https://app.asana.com/0/1201016280880500/1202470994952468/f) task, and work on it later.

**Pull request merged**
