### PR TITLE
Improve Storage Performance

### LINKED ISSUE #46: Poor Performance on Mobile Device
Extremely poor performance on mobile devices. Need time to investigate the root cause. 

- It is highly possible that the `Filesystem` on the Android device is not fast enough to rapidly query multiple times.
  - Possible fix: merge the information tuples into a large json file.
  - Possible fix: use sqlite instead.
- Media data use base64 encoding to pass around instead of file object with source URI.

## Roadmap

- [x] ~~Use `` instead of `<ion-img>` for better performance.~~
- [x] ~~Merge the information tuples into a large json file.~~ This require new "equal" class to check the equality. Greatly add complexity.
- [x] Call `Storage.refresh$()` only on initialization.
  - [x] Remove calling `Storage.refresh$()` on `Storage.add$()`.
  - [x] ~~Remove calling `Storage.refresh$()` on `Storage.remove$()`.~~ This require new "equal" class to check the equality. Greatly add complexity.
- [x] Generate the thumbnail of the media asset on captured.

### PR DESCRIPTION
**Pull request by seanwu1105**
Fix #46.

Add new dependency [`image-blob-reduce`](https://github.com/nodeca/image-blob-reduce) to generate thumbnail. However, the library does NOT have type hints.

### CODE REVIEW

**Comment by bafu** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ src/app/utils/storage/storage.ts  24
+ src/app/services/data/information/information-repository.service.ts  3
+ src/app/services/data/proof/proof-repository.service.ts  2
+ src/app/services/data/signature/signature-repository.service.ts  3
+ src/app/pages/information/information.page.ts  3
+ src/app/services/data/caption/caption-repository.service.ts  1
         

Coverage decreased per file
===========================
- src/app/pages/storage/storage.page.ts  -14
- src/app/utils/rx-operators.ts  -33
- src/app/app.component.ts  -4
- src/app/pages/proof/proof.page.ts  -1
         

Complexity decreasing per file
==============================
+ src/app/utils/encoding/encoding.ts  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6109946&bid=19998030)

**Comment by bafu** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/app/utils/encoding/encoding.ts  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6109946&bid=19998030)

**Comment by bafu** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/app/utils/encoding/encoding.ts  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/numbersprotocol/capture-lite/pullRequest?prid=6109946&bid=19998030)

**Review by shc261392 — APPROVED** [review]
Haven't done any manual testing for the performance improvement, but everything seems to be in order.

**Pull request merged**
