### PR TITLE
Feat rebrand settings page

### PR DESCRIPTION
**Pull request by sultanmyrza**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201016280880500/1203661382325443) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by tammyyang — COMMENTED** [review]
@sultanmyrza it's not something big, but just wondering if we want to try using ngIf instead of ngrxPush for the device and location toggles? (just [found this](https://github.com/ngrx/platform/issues/3342), not sure if it affects the performance)

**Comment by sultanmyrza** [comment]
> @sultanmyrza it's not something big, but just wondering if we want to try using ngIf instead of ngrxPush for the device and location toggles? (just [found this](https://github.com/ngrx/platform/issues/3342), not sure if it affects the performance)

@tammyyang `*ngIf` and `ngrxPush` serve different purposes.

By #ChatGPT 😅
> `ngrxPush` is a custom directive that can be used with the ngrx library, which is a powerful library for managing the state of an Angular application. ngrxPush can be used to automatically push new state to the store whenever a certain condition is met. For example, you can use ngrxPush to push the value of an input field to the store whenever the input changes.
`ngIf` is a built-in Angular directive that is used to conditionally render a piece of HTML based on a boolean expression. For example, you can use ngIf to show or hide a certain element based on the value of a variable.

One way to speed up `SettingsPage.ts` can be to change the `chageDetection` strategy to `ChangeDetectionStrategy.OnPush`. 

By default, Angular runs change detection every x moment to update UI if there were any changes. We can set `ChangeDetectionStrategy.OnPush` so Angular will update UI only when we tell Angular to update.

One example is [custom-camera.page.ts](https://github.com/numbersprotocol/capture-lite/blob/732dcc56da7d8737d60ef271aee2405a141394c4/src/app/features/home/custom-camera/custom-camera.page.ts#L42)

**Comment by tammyyang** [comment]
@sultanmyrza thank you for the explanation. I actually received the suggestion from ChatGPT, and it insists that using ngif may provide cleaner and better performance. That's why I tried to check and found that there was indeed a performance concern related to ngrx

```
<ion-item>
      <ion-label>{{ t('collectDeviceInfo') }}</ion-label>
      <ion-toggle *ngIf="isDeviceInfoCollectionEnabled$ | async as isDeviceInfoEnabled" 
        [checked]="isDeviceInfoEnabled"
        (ionChange)="setDeviceInfoCollection($event)"
        slot="end"
      ></ion-toggle>
    </ion-item>
    <ion-item>
      <ion-label>{{ t('collectLocationInfo') }}</ion-label>
      <ion-toggle *ngIf="isLocationInfoCollectionEnabled$ | async as isLocationInfoEnabled" 
        [checked]="isLocationInfoEnabled"
        (ionChange)="setLocationInfoCollection($event)"
        slot="end"
      ></ion-toggle>
    </ion-item>

```

**Comment by sultanmyrza** [comment]
> @sultanmyrza thank you for the explanation. I actually received the suggestion from ChatGPT, and it insists that using ngif may provide cleaner and better performance. That's why I tried to check and found that there was indeed a performance concern related to ngrx
> 
> ```
> <ion-item>
>       <ion-label>{{ t('collectDeviceInfo') }}</ion-label>
>       <ion-toggle *ngIf="isDeviceInfoCollectionEnabled$ | async as isDeviceInfoEnabled" 
>         [checked]="isDeviceInfoEnabled"
>         (ionChange)="setDeviceInfoCollection($event)"
>         slot="end"
>       ></ion-toggle>
>     </ion-item>
>     <ion-item>
>       <ion-label>{{ t('collectLocationInfo') }}</ion-label>
>       <ion-toggle *ngIf="isLocationInfoCollectionEnabled$ | async as isLocationInfoEnabled" 
>         [checked]="isLocationInfoEnabled"
>         (ionChange)="setLocationInfoCollection($event)"
>         slot="end"
>       ></ion-toggle>
>     </ion-item>
> ```

@tammyyang, thats an interesting finding. Can you please tell me how you measure performance? 😇

**Comment by tammyyang** [comment]
BTW, I fully understand sometimes the suggestions provided by ChatGPT is not 100% correct (it provides me some source code yesterday that cannot be executed under nodejs14.x at all :P)

However, as you know, many of the source code of Capture were developed at very early stage. We didn't expect this App will survive for such a long time and become the main product of Numbers Protocol. Therefore, I think it is time to revisit some old source code and fix performance issues gradually. 

That's why I may from time to time to raise questions to you during the code review, and you may find that my questions do not have the direct relationship to the issues you are fixing. I believe it's good that we revisit the source code of Capture App, have more discussions and improve the quality :).

**Comment by tammyyang** [comment]
@sultanmyrza  what about we use the browser dev tool to execute and 
1. calculate the time from pressing the toggle to the actual change and measure? 
2. check if the resource is released after 5min?

Even though it's not the most ideal way, since this is a small feature, I think if there are no big difference, we can survive with the current implementations.

**Review by tammyyang — APPROVED** [review]

**Review by tammyyang — APPROVED** [review]
b227b0dd3f91f49e13ed2f469dfbbe18a1f469a7

**Review by tammyyang — CHANGES_REQUESTED** [review]
Update review process (mis-press the approve button)

**Review by tammyyang — CHANGES_REQUESTED** [review]
@sultanmyrza for the src/assets/i18n/en-us.json file, I found the text are still not consistent. For example, it is Information "P"rovider but Collect "d"evice "i"nfo.

Maybe we only keep the first letter Capitalized and the rest in small cases?

**Comment by sultanmyrza** [comment]
> @sultanmyrza for the src/assets/i18n/en-us.json file, I found the text are still not consistent. For example, it is Information "P"rovider but Collect "d"evice "i"nfo.
> 
> Maybe we only keep the first letter Capitalized and the rest in small cases?

@tammyyang , becaue Information Provider was not on Menu items I didn't changed it. This PR is related to Menu items only. Therefore I created asana [card](https://app.asana.com/0/1201016280880500/1203685808700607/f) for another PR in future.

**Comment by sultanmyrza** [comment]
> BTW, I fully understand sometimes the suggestions provided by ChatGPT is not 100% correct (it provides me some source code yesterday that cannot be executed under nodejs14.x at all :P)
> 
> However, as you know, many of the source code of Capture were developed at very early stage. We didn't expect this App will survive for such a long time and become the main product of Numbers Protocol. Therefore, I think it is time to revisit some old source code and fix performance issues gradually.
> 
> That's why I may from time to time to raise questions to you during the code review, and you may find that my questions do not have the direct relationship to the issues you are fixing. I believe it's good that we revisit the source code of Capture App, have more discussions and improve the quality :). Thank you very much for your patience and efforts!

@tammyyang, yes actually I was thinking about that as well we might try to use `ChangeDetectionStrategy.OnPush` on critical components first and gradually improve app performance.

There are many ways to improve performance, especially in the angular world.

When deadlines are tight I try to not touch what is already working 😅, because changing something in the left ear might paralyze the fingers on the right foot toe 😅.

Also during the new year holiday I read about [Tips to Improve Ionic Angular App Performance](https://ionic.io/blog/5-tips-to-improve-ionic-angular-app-performance) official ionic blog post, it can be a good starting point as well.

**Comment by tammyyang** [comment]
> @sultanmyrza what about we use the browser dev tool to execute and
> 
> 1. calculate the time from pressing the toggle to the actual change and measure?
> 2. check if the resource is released after 5min?
> 
> Even though it's not the most ideal way, since this is a small feature, I think if there are no big difference, we can survive with the current implementations.

@sultanmyrza  but at least can we try this? I think it will be good that we experiment one by one every time.

**Comment by sultanmyrza** [comment]
> > @sultanmyrza what about we use the browser dev tool to execute and
> 
> > 
> 
> > 1. calculate the time from pressing the toggle to the actual change and measure?
> 
> > 2. check if the resource is released after 5min?
> 
> > 
> 
> > Even though it's not the most ideal way, since this is a small feature, I think if there are no big difference, we can survive with the current implementations.
> 
> 
> 
> @sultanmyrza  but at least can we try this? I think it will be good that we experiment one by one every time.

@tammyyang sure we can try. I need to google it on how to measure performance with chrome dev tools. If you have any docs or knowledge please share with me 😊

**Comment by tammyyang** [comment]
> > @sultanmyrza for the src/assets/i18n/en-us.json file, I found the text are still not consistent. For example, it is Information "P"rovider but Collect "d"evice "i"nfo.
> > Maybe we only keep the first letter Capitalized and the rest in small cases?
> 
> @tammyyang , becaue Information Provider was not on Menu items I didn't changed it. This PR is related to Menu items only. Therefore I created asana [card](https://app.asana.com/0/1201016280880500/1203685808700607/f) for another PR in future.

@sultanmyrza These are from this commit https://github.com/numbersprotocol/capture-lite/pull/2461/commits/6dac13e1f9b7bc10e404d44a4f13cc6d108f51f3 and is included in this PR. So, I think it should be updated in this code review.

**Comment by sultanmyrza** [comment]
> > > @sultanmyrza for the src/assets/i18n/en-us.json file, I found the text are still not consistent. For example, it is Information "P"rovider but Collect "d"evice "i"nfo.
> 
> > > Maybe we only keep the first letter Capitalized and the rest in small cases?
> 
> > 
> 
> > @tammyyang , becaue Information Provider was not on Menu items I didn't changed it. This PR is related to Menu items only. Therefore I created asana [card](https://app.asana.com/0/1201016280880500/1203685808700607/f) for another PR in future.
> 
> 
> 
> @sultanmyrza These are from this commit https://github.com/numbersprotocol/capture-lite/pull/2461/commits/6dac13e1f9b7bc10e404d44a4f13cc6d108f51f3 and is included in this PR. So, I think it should be updated in this code review.

@tammyyang sure I will update in this PR 😊

**Comment by tammyyang** [comment]
> > > @sultanmyrza what about we use the browser dev tool to execute and
> > 
> > 
> > > 
> > 
> > 
> > > 1. calculate the time from pressing the toggle to the actual change and measure?
> > 
> > 
> > > 2. check if the resource is released after 5min?
> > 
> > 
> > > 
> > 
> > 
> > > Even though it's not the most ideal way, since this is a small feature, I think if there are no big difference, we can survive with the current implementations.
> > 
> > 
> > @sultanmyrza  but at least can we try this? I think it will be good that we experiment one by one every time.
> 
> @tammyyang sure we can try. I need to google it on how to measure performance with chrome dev tools. If you have any docs or knowledge please share with me 😊

Is this helpful?

```
You can use the Chrome Developer Tools to test the performance of your Ionic code. Here's a general workflow you can use:

1. Open your Ionic app in Chrome by visiting the localhost URL or by running "ionic serve" command on your development machine.

2. Open the Chrome Developer Tools by right-clicking on the page and selecting "Inspect," or by pressing F12 on your keyboard.

3. Once the Developer Tools are open, select the "Performance" tab. This will open a new panel that allows you to profile the performance of your application.

4. Click the "Start Profiling" button to begin collecting performance data. Perform the actions in your app that you want to test (e.g. navigating to a specific page, performing a specific task, etc.).

5. Once you've finished performing the actions, click the "Stop Profiling" button. The Developer Tools will display a summary of the performance data, including information about CPU usage, network requests, and layout rendering.

6. You can use the "Call Tree" or "Bottom-Up" tabs to view the specific function calls that were made during the profiled period and see how much time each of them took.

7. The "Timeline" tab will allow you to see how different events such as styles, layouts, scripting, painting, etc are happening on your application, this allow you to identify which events take too much time or happened frequently that could affect your performance.

8. Analyze the data to identify any bottlenecks or areas that need improvement in your app. Then make the necessary changes in your code and repeat the process to see if your performance improves.

Please keep in mind that this is just a general workflow and the exact steps may vary depending on your specific use case and the version of Chrome Developer Tools that you're using.
```

**Comment by sultanmyrza** [comment]
closed in favor of https://github.com/numbersprotocol/capture-lite/pull/2499

**Pull request closed without merging**
